### ISSUE TITLE
`showOpenDialog` need disable `canChooseFiles` explicitly

### ISSUE THREAD

**Issue by xsfour** [skpm/dialog#11]
Although the `openFile` attribute is not set, files can still be selected:
```javascript
  showOpenDialogSync({ properties: ['openDirectory'] })
```

From the [document](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/UsingtheOpenandSavePanels/UsingtheOpenandSavePanels.html), the `canChooseFiles` option is enabled by default:

> The NSOpenPanel object returned by the openPanel method is configured with the following default options:
> - **File selection: enabled**
> - Directory selection: disabled
> - Resolve aliases: enabled
> - Multiple selection: disabled
> - Show hidden files: disabled
> - File packages treated as directories: disabled
> - Can create directories: disabled

I think we need a new `property` to explicitly disable the `canChooseFiles` option.

**Comment by mathieudutour** [comment]
ah that was a bug. Should be fixed in v0.4
