### ISSUE TITLE
Pressing "Cancel" button doesn't seem to actually close the dialog

### ISSUE THREAD

**Issue by romannurik** [skpm/dialog#4]
Using `showOpenDialog` and then pressing Cancel in the system file picker doesn't seem to actually close the dialog :-/

**Comment by romannurik** [comment]
This seems to be the case only if you provide a callback.

**Comment by mathieudutour** [comment]
fixed in 0.2.1

**Comment by mathieudutour** [comment]
I'm struggling to reproduce. But I need to do a nasty hack when there is both a document and a callback. Is your OS in English?

**Comment by romannurik** [comment]
Hey Mathieu, yeah my OS is in English. FWIW I'm currently just not using the callback as a workaround; it seems fine since it's synchronous / JS execution seems to be paused while the dialog is up.

**Comment by mathieudutour** [comment]
I should be fixed in v0.2.6
