### ISSUE TITLE
Save dialog: Giving filename but not selecting any file or folder results in error

### ISSUE THREAD

**Issue by wousser** [skpm/dialog#7]
From documentation:
```
defaultPath String (optional) - Absolute directory path, absolute file path, or file name to use by default.
```
When opening the dialog with an absolute directory path or file path, the dialog opens with that folder. The file's name will be the file path's name. If the user changes the name within the dialog, the callback's filepath is the absolute file path + user's given filename. Instead of absolute directory path + user's given filename.

code:
```
var filePath = dialog.showSaveDialog({
    defaultPath: document.path
  })
```

Actual Output:
document.path: '/Users/username/Projects/project/file.sketch'
filePath:  /Users/username/Projects/project/file.sketch/name given by user.txt

Expected Output:
document.path: '/Users/username/Projects/project/file.sketch'
filePath:  /Users/username/Projects/project/name given by user.txt

User does not select anything, only changes the filename.
![image](https://user-images.githubusercontent.com/1159336/48844662-787bdb00-edd5-11e8-887e-1a9b77b3b7dd.png)

**Comment by mathieudutour** [comment]
that's because the default path is `'/Users/username/Projects/project/file.sketch'`. Try:

```js
const path = require('path')

var filePath = dialog.showSaveDialog({
    defaultPath: path.dirname(document.path)
  })
```
